##################
### production ###
##################

# base image
FROM nginx:1.13.9-alpine

# copy artifact build from the 'build environment'
COPY ./dist/ng-zorro-antd /usr/share/nginx/html

ADD nginx.conf /etc/nginx/nginx.conf

# expose port 80
EXPOSE 80

# run nginx
CMD ["nginx", "-g", "daemon off;"]


# docker build -f Dockerfile-zorro-antd -t 172.16.111.21:5000/docs-zorro-antd .
# docker run -d --name docs-zorro-antd -p 9903:80 --rm 172.16.111.21:5000/docs-zorro-antd
