##################
### production ###
##################

# base image
FROM nginx:1.13.9-alpine

# copy artifact build from the 'build environment'
COPY ./dist/design /usr/share/nginx/html

ADD nginx.conf /etc/nginx/nginx.conf

# expose port 80
EXPOSE 80

# run nginx
CMD ["nginx", "-g", "daemon off;"]


# docker build -f Dockerfile-design -t 172.16.111.21:5000/docs-design .
# docker run -d --name docs-design -p 9906:80 --rm 172.16.111.21:5000/docs-design
